version: '3.9'

services:
  user-service:
    build: .
    container_name: user-service-express
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./keys:/usr/src/app/keys:ro
      - ./.env:/usr/src/app/.env:ro
      - ./jest.config.js:/usr/src/app/jest.config.js:ro
    networks:
      - backboard-network
networks:
  backboard-network:
    external: true
