export const TYPES = {
  DataSource: Symbol.for('DataSource'),
  Logger: Symbol.for('Logger'),
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  UserController: Symbol.for('UserController'),
  AuthService: Symbol.for('AuthService'),
  AuthController: Symbol.for('AuthController'),
  GoogleAuthService: Symbol.for('GoogleAuthService'),
  HealthService: Symbol.for('HealthService'),
  HealthController: Symbol.for('HealthController'),
  EventPublisher: Symbol.for('EventPublisher'),
  UserEventsPublisher: Symbol.for('UserEventsPublisher'),
  RoleRepository: Symbol.for('RoleRepository'),
  RoleService: Symbol.for('RoleService'),
  RoleController: Symbol.for('RoleController'),
  PermissionRepository: Symbol.for('PermissionRepository'),
  PermissionService: Symbol.for('PermissionService'),
  PermissionController: Symbol.for('PermissionController'),
  UserAuthService: Symbol.for('UserAuthService'),
  JwksController: Symbol.for('JwksController'),
};

